# Generated by Django 3.2.8 on 2023-11-01 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='Nombre')),
                ('title', models.CharField(max_length=10000, verbose_name='Título')),
                ('reference', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Referencia bibliográfica')),
            ],
            options={
                'verbose_name': 'Fuente clásica',
                'verbose_name_plural': 'Fuentes clásicas',
            },
        ),
        migrations.RemoveField(
            model_name='hipotext',
            name='fuentes_clasicas',
        ),
        migrations.RemoveField(
            model_name='hipotext',
            name='fuentes_documentales',
        ),
        migrations.RemoveField(
            model_name='hipotext',
            name='otras_fuentes',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.AddField(
            model_name='classicsource',
            name='hipotext',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hipotext_classic_sources', to='catalog.hipotext'),
        ),
    ]
