# Generated by Django 3.2.8 on 2023-11-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20231101_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='Nombre')),
                ('title', models.CharField(max_length=10000, verbose_name='Título')),
                ('reference', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Referencia bibliográfica')),
                ('hipotext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hipotext_other_sources', to='catalog.hipotext')),
            ],
            options={
                'verbose_name': 'Otra fuente',
                'verbose_name_plural': 'Otras fuentes',
            },
        ),
        migrations.CreateModel(
            name='DocumentarySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='Nombre')),
                ('title', models.CharField(max_length=10000, verbose_name='Título')),
                ('reference', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Referencia bibliográfica')),
                ('hipotext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hipotext_documentary_sources', to='catalog.hipotext')),
            ],
            options={
                'verbose_name': 'Fuente doxumental',
                'verbose_name_plural': 'Fuentes documentales',
            },
        ),
    ]
