# Generated by Django 3.2.8 on 2023-11-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_documentarysource_othersource'),
    ]

    operations = [
        migrations.AddField(
            model_name='hipotext',
            name='adittional_comments',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Comentarios adicionales'),
        ),
    ]
