# Generated by Django 3.2.8 on 2023-11-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_hipotext_adittional_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='hipotext',
            name='innecesary_field',
            field=models.IntegerField(choices=[], default=1, verbose_name='Campo innecesario solo para funcionamiento'),
        ),
    ]
