# Generated by Django 3.2.8 on 2023-11-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_hipotext_innecesary_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hipotext',
            name='adittional_comments',
        ),
    ]
