# Generated by Django 3.2.8 on 2023-11-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_hipotext_adittional_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hipotext',
            name='innecesary_field',
            field=models.IntegerField(choices=[(1, 1)], default=1, verbose_name='Campo innecesario solo para funcionamiento'),
        ),
    ]
